export { default as Article } from './article/Article'
export { default as Brand } from './brand/Brand'
export { default as CalltoAction } from './calltoAction/CalltoAction'
export { default as Features } from './features/Features'
export { default as Navbar } from './navbar/Navbar'